language: go
go:
- '1.10'
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=ocadotechnologygitlab
  - VCS_SOURCE="https://github.com/${TRAVIS_REPO_SLUG}"
  - SNYK_MODE=WARN
  - secure: "CXN9hp2RdDv9FhiENAhlGO4VbDFCqlDBXaWG67NBjzXig6fRpU7E3RiXdZPz7iSCSN2ALPF5F5UHWqx102eUoPliLO6ytFH2BBXggiDiyAa95d8KJ7iNLE7hhzQfpLfNAtX74xdYHmHfgayT2qLE2rtEGAlCxwoFFi+SnQaFYHpjMAu8x2sScruii8uUcCFAs7YpW/7pGGKUeto9G0YBl9kh9okqRQ+GZOTVnhtqbHJHRLWJmwkBILRctDCpu9/DyZQVNP+8uysuohFRUG1STjSa0gjpP1jycnD6MoGovRZQ8ityK2eprzVXLdPLp2Bee1xutRvwe2ssObkBOBQuMbMARiRf0OjIYveZf5sZF8y2GOuVwL14yApo346+m6Bq5rgJCLh11QsnOtco9/MY+gXcfM4bitZQHyoAUu+ak96ZrCAlRvYOjnxIaA82t/jMkLjQiZC+Ja2zzL+sl+manUlvOwrySvsdJ0RrH609TuWvktZJwBVjsNS36LpOAHhEdxK+Iry9eO3jgLUzhqsO69atANIehulyhkzSAcXNLS3Bj27BjSyXsZ+QUNuj9pTxBou7YnnqWC4CkOEn7Bjp0W4recbxTT8b5xu+TofVTdRFC9tcINidxvFSvuXOGP9XICgmgLf2i0l3iNKrDTMDI0YWJNjGEAy5VGbj7XuQ54E="
  - secure: "YH3T5VrH6HGeCdutyZaDHjFxU1kMOb1rtCMO6zPGdrYRgTHU/WrQAqBwygk6Zf+vDDs2X3tgZSIZKnLKPsy5otndEkEUMfdx6m5Os0FOqSqYXeek1Av9BjZKP7vvR72l3vCGf+1smzgvVRFs1s1CVo0dXEfZPCkwfdP31YNRXmkoK4vehAkSZYJ5B8CjwDKe4JXxcmgZHmnLQUHIs7wFGKixZLZ2PYTSpGXb5g5sIxUq8lQuY4MSc1GDIfTBN8ruqlopq+qn4TeC4BQoYtszt5M9T6rN3jqb2BmNEb8wcVNpLxyNzMEF+iTNA9m4S9wlZ/6kC+2xdOJd7XcdbqZcJ9A36zjEH9KYK+U8uBThMnMk8NlcwNRiWJDvmZTSHFAKtXtSK1Rld+WHVu5J2UOTyxkIgGBF3xenMoIJ8HF+6A6zLV6b5nurVfyo+5gY4gQZ+3Z8Xf9W75jGj3Qo5eyo3Vkh5Ej3CTPO+sIg0ycikmFuXJXiDAStFYf/T1emZqdZu54nYivWGKRQdG7u2Z3UZZiIdUssMRFHKwMzU8FGy7YlAWQugebONBvsOD8dLcwDxftTnKryZJFhs6dkYgUuAKk/AsM0lcRHS/EfNczOPwrEMEg52qUBASIOff6r9tcUOYwz31xQkKxDcM5kMhQaCLp79bEn89IDZGJYq/yEBBE="
  - secure: "ahurRTRXQ2s9lW1GrJmfWM+JE/11USa//m0fRMUfAs5b3QmotFl0FkYwxHxXdcNo3Xk5KTJjBQV1QzAJWtA+oFVYrNFLofJRiU1l0M53E2g2px91ZgfCYD1PwFkcVJy8EunBo82qaTQBzssY8ZE0/1RS6z01yf8fIbhtkXgGTbEd+Q3NKSXJBWDWx6ThswM04ThvqCL/zr6esJPaR9zl0hLagBl50SlQdYvmkQM9lxvhEbC9mcYvkU36//h2xFQzbadrg8kg3QtC2uQmH3nJfCU8oyzpGLhZb/GnOd/XGopa4ea42z8j/Z9kk2/Y2ztaqHr12F5bDC2sFNaJzbmFQarr2aIGNp2YRDocxeU3Huhy0MtEJx5PeTd/WXysEws65icIZlzKVu1tEkNn9DdP2hI/+7vue6ODzE4lP4nhbTZcnNHbwxOfK7bsTu9UCIajQzxpWiua1lYyUPWl29O0mbQRtlXbaM3MnAEgH1J4UnanymIhzw3Pc8UzxakMFKCXJtCzAzSX29yvSFT0DdocVvQqTwYxpv3eTaMFy0jkpOBrK366qTA3yGQKgMzMNNai54lwINqqhxzMyY5DGMwDG91PHGAXMPZbRFjMZCWwFHT3XH2XUjfTKl9sLTn/EX2EyO/lyztNQJVKVXwnpQ6DGyP1lev1BhbL3ZSRvqs6pV4="
install:
- go get github.com/progrium/basht
script:
- npm install -g snyk
- basht ./gatekeeper.bash
- ./.travis/docker-build.sh
after_script:
- docker images
deploy:
  provider: script
  script: ./.travis/docker-push.sh
  on:
    branch: master
    tags: true